models/guapos.py
from flask_login.mixins import UserMixin
from db.db_engine import db


class Guapos(db.Model, UserMixin):  # type: ignore

    # campos
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    name = db.Column(db.String(30), nullable=False)
    apellido = db.Column(db.String(30), nullable=False)
    guapura = db.Column(db.Integer, nullable=True)
    soltero = db.Column(db.Boolean, nullable=False)
    password = db.Column(db.String(100), nullable=False)
    ispapucho = db.Column(db.Boolean, nullable=False)

    def __init__(self, name, apellido, guapura, soltero, password, ispapucho) -> None:

        self.name = name
        self.apellido = apellido
        self.guapura = guapura
        self.soltero = soltero
        self.password = password
        self.ispapucho = ispapucho

    def __repr__(self):
        return f"""{self.name}, {self.apellido}, {self.guapura}, {self.ispapucho}"""
    

forms/form_guapo.py
from flask_wtf import FlaskForm
from wtforms.fields.numeric import IntegerField
from wtforms.fields.simple import PasswordField, StringField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError

class GuapuraForm(FlaskForm):
    apellido = StringField(
        "apellido del guapo",
        validators=[InputRequired(), Length(min=3, max=20)],
        render_kw={"placeholder": "Escribe el apellido del guapo"},
    )

    guapura = IntegerField("Type guapura", validators=[InputRequired()])


    submit = SubmitField("Enviar")

    def validate_guapura(self, guapura):
        if guapura.data < 0 or guapura.data > 10:
            raise ValidationError("GUapura es del 1 al 10")

forms/form_login.py
from flask_wtf import FlaskForm
from wtforms.fields.choices import SelectField
from wtforms.fields.simple import PasswordField, StringField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError

from models.guapos import Guapos


class LoginForm(FlaskForm):	
	apellido = StringField("apellido del guapo", validators=[InputRequired(), Length(min=3, max=20)], render_kw={"placeholder" : "Escribe el apellido del guapo"})	

	password = PasswordField("Escribe password", validators=[InputRequired(), Length(min=2, max=10)])

	submit = SubmitField("Enviar")

forms/form_register.py
from flask_wtf import FlaskForm
from wtforms.fields.choices import SelectField
from wtforms.fields.simple import PasswordField, StringField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError

from models.guapos import Guapos


class RegisterForm(FlaskForm):

    name = StringField(
        "Nombre del guapo",
        validators=[InputRequired(), Length(min=3, max=20)],
        render_kw={"placeholder": "Escribe el nombre del guapo"},
    )

    apellido = StringField(
        "apellido del guapo",
        validators=[InputRequired(), Length(min=3, max=20)],
        render_kw={"placeholder": "Escribe el apellido del guapo"},
    )

    soltero = SelectField(
        "Eres soltero", choices=[("1", "Si"), ("2", "No")], validators=[InputRequired()]
    )

    password = PasswordField(
        "Escribe password", validators=[InputRequired(), Length(min=2, max=10)]
    )

    submit = SubmitField("Enviar")

    # validate_ + apellido
    def validate_apellido(self, apellido):
        value_apellido = apellido.data
        user = Guapos.query.filter_by(apellido=value_apellido).first()
        if user:
            raise ValidationError("Necesita ser apellido distinto")

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from db.db_engine import db
from routes.auth import auth
from routes.vip import vip
from db.login import login_manager
from flask_migrate import Migrate
from db.db_engine import db

app = Flask(__name__)

app.config.from_object("config.BaseConfig")

app.register_blueprint(auth)
app.register_blueprint(vip)

# Intercepcion de mundos a la db dando settings
SQLAlchemy(app)
Bcrypt(app)
login_manager.init_app(app)
Migrate(app, db)

# creando las tablas con los settings dados
with app.app_context():
    db.create_all()


if "__main__" == __name__:
    app.run(debug=True)

routes/auth.py
from flask import Blueprint
from flask.helpers import url_for
from flask.templating import render_template
from flask_login.utils import logout_user
from werkzeug.utils import redirect

from forms.form_register import RegisterForm
from models.guapos import Guapos
from forms.form_login import LoginForm
from db.db_engine import db
from db.bcrypt import bcrypt
from flask_login import login_user


auth = Blueprint("auth", __name__)


@auth.route("/")
def home():
    if not Guapos.query.filter_by(apellido="algas").first():
        password_hash = bcrypt.generate_password_hash("123")
        el_papucho = Guapos("balbino", "algas", 10, 1, password_hash, True)
        db.session.add(el_papucho)
        db.session.commit()
    return render_template("auth.html")


@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("auth.home"))


@auth.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        apellido = form.apellido.data
        passw = form.password.data
        user = Guapos.query.filter_by(apellido=apellido).first()
        if user:
            if bcrypt.check_password_hash(user.password, passw):
                login_user(user)
                return redirect(url_for("vip.home"))
    return render_template("login.html", form=form)


@auth.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        name = form.name.data
        apellido = form.apellido.data
        passsword = form.password.data
        passsword_hashed = bcrypt.generate_password_hash(passsword)
        soltero = True if form.soltero.data == "1" else False

        newGuapo = Guapos(name, apellido, None, soltero, passsword_hashed)
        db.session.add(newGuapo)
        db.session.commit()
        return redirect(url_for("auth.login"))

    return render_template("register.html", form_register=form)

routes/vip.py
from flask import Blueprint, url_for, redirect
from flask.templating import render_template
from flask_login import current_user
from flask_login.utils import login_required
from forms.form_guapo import GuapuraForm
from models.guapos import Guapos
from db.db_engine import db

vip = Blueprint("vip", __name__, url_prefix="/vip")


@vip.route("/")
@login_required
def home():
    return render_template("vip.html", user=current_user)


@vip.route("/guapos")
@login_required
def guapos():
    return render_template("home.html", user=current_user, rows=Guapos.query.all())


@vip.route("/change_guapura/<int:id_guapo>", methods=["GET", "POST"])
@login_required
def change_guapura(id_guapo):
    if current_user.ispapucho:
        form = GuapuraForm()
        guapo = Guapos.query.get(id_guapo)

        if form.validate_on_submit():
            guapo.apellido = form.apellido.data
            guapo.guapura = form.guapura.data
            db.session.add(guapo)
            db.session.commit()
            return redirect(url_for("vip.guapos"))

        form.apellido.data = guapo.apellido
        form.guapura.data = guapo.guapura
        

        return render_template("papucho_change.html", user=guapo, form=form) 
    else:
        return redirect(url_for("vip.home"))

templates/auth.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Authentication</title>
</head>
<body>
	<a href="{{ url_for('auth.register') }}">Registrarse</a>
	<a href="{{ url_for('auth.login') }}">Login</a>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Hola{{user.name}}</h1>
    <table>
        <tr>
            <th>
                Name
            </th>
            <th>
                Apellido
            </th>
            <td>
                Guapura 1-10
            </td>
            <td>Esta soltero</td>
        </tr>
        {% for row in rows %}
        <tr>
            <td>{{ row.name }}</td>
            <td>{{ row.apellido }}</td>
            <td>{{ row.guapura }}</td>
            <td>{{ row.soltero }}</td>
	    {% if user.ispapucho %}
		<td><a href="{{url_for('vip.change_guapura', id_guapo=row.id)}}" >change guapura</a></td>
	    {% endif %}
        </tr>
        {% endfor %}
    </table>

    <h1>{{ val }}</h1>
    <h1>{{ val_2 }}</h1>

</body>

</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Login</title>
</head>
<body>
	<h1>Lofeate</h1>
	<form action="{{ url_for('auth.login') }}" method="post">
		{{ form.hidden_tag() }}
		{{ form.apellido.label }}
		{{ form.apellido }}
		{{ form.password.label }}
		{{ form.password }}
		{{ form.submit }}
		
	</form>
</body>
</html>

templates/papucho_change.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Papucho_change</title>
</head>

<body>
    <form action="{{ url_for('vip.change_guapura', id_guapo=user.id) }}" method="post">
        {{ form.hidden_tag()  }}
        {{ form.apellido.label  }}
        {{form.apellido}}
        {{form.guapura.label }}
        {{form.guapura}}
        {{form.submit}}
    </form>
</body>

</html>

templates/register.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Register</title>
</head>
<body>
	<h1>Registrate</h1>
	<form action="{{ url_for('auth.register')}}" method="post">
		{{ form_register.hidden_tag() }}
		{{ form_register.name.label }}
		{{ form_register.name }}
		{{ form_register.apellido.label }}
		{{ form_register.apellido }}
		{{ form_register.password.label }}
		{{ form_register.password }}
		{{ form_register.soltero.label }}
		{{ form_register.soltero }}
		{{ form_register.submit }}
		
	</form>

</body>
</html>

templates/vip.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{{ user.apellido }}</title>
</head>
<body>
    <h1>hello {{ user}}</h1>
	<a href="{{ url_for('auth.logout') }}">logout</a>
	<a href="{{ url_for('vip.guapos')  }}">view guapos</a>
</body>
</html>